### PR TITLE
Add support for Visual Studio 2017

### PR DESCRIPTION
**Pull request by bsivanov**
This aims to add support for Visual Studio 2017. Though I tested it on Visual Studio 2012 - 2017, there are parts I am not sure about, so I would like second opinion:

- source.extension.vsixmanifest file contained some strange CustomExtension parts, e.g. 
`<CustomExtension Type="Microsoft Office SmartArt Graphic Color Variation">Templates\default.gcsx</CustomExtension>`
which I've migrated as Assets in the new format:
`<Asset Type="Microsoft Office SmartArt Graphic Color Variation" d:Source="File" Path="Templates\default.gcsx" />`
I am not sure this is the correct format, nor how to test whether the migration is successful.
- When opening VSPackage.resx, the resource names are listed as not valid 
    
    > The resource name '107' is not a valid identifier.

    I am not sure why.

Despite these problems, the extension seems to work pretty well. @pugwonk, I count on you for review.

### CODE REVIEW

**Comment by ridomin** [comment]
any plans to submit the VS2017 extension to the marketplace?

**Comment by bsivanov** [comment]
@ridomin Given that this is not even commented from the repo owners for 3 months, yes. 

For now, you can use the version I pre-built locally: [https://1drv.ms/u/s!Amp5JXlYDuqQg9dPJRBo0G3OAw7Jdg](url)

Some teammates and me are using it for months without any issues, it's compatible with VS 2012-2017.

**Comment by BroVic** [comment]
@bsivanov Hi. That link didn't work...

**Comment by bsivanov** [comment]
This is the correct link: [https://1drv.ms/u/s!Amp5JXlYDuqQg9dPJRBo0G3OAw7Jdg](https://1drv.ms/u/s!Amp5JXlYDuqQg9dPJRBo0G3OAw7Jdg), I am sorry.

**Comment by bsivanov** [comment]
Hello guys, the forked extension with support for Visual Studio 2017/2015/2013/2012 is published here: [Open XML Package Editor for Modern Visual Studios](https://marketplace.visualstudio.com/items?itemName=bsivanov.OpenXMLPackageEditorforVisualStudio)

If anyone from Microsoft is reading this - please let me know if there are some problems with the license. I preserved your copyright messages, and my intention is to ease the work of the OpenXML devs, and not to steal users from this project. 

I would happily unpublish the extension to avoid clutter, in case someone merge my pull request here.

**Comment by bsivanov** [comment]
I am closing this as outdated. My fork is gaining traction, if needed I can merge the relevant changes here as well.

**Pull request closed without merging**
